class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  # skip_before_action :authenticate_user!, only: [:index]


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:character_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:character_name, :head, :armor, :shoes, :mainhand, :offhand])
  end

  before_action :set_items

  private
  def set_items
    # @heads = ["Beginner's Mercenary Hood", "Adventurer's Helmet", "Explorer's Hat", "Novice's Mercenary Hood", "Novice's Scholar Cowl", "Novice's Soldier Helmet", "Journeyman's Mercenary Hood" ]
    @heads = [
      "Beginner's Mercenary Hood",
      "T2",
      "Adventurer's Helmet",
      "Explorer's Hat",
      "Novice's Mercenary Hood",
      "Novice's Scholar Cowl",
      "Novice's Soldier Helmet",
      "T3",
      "Journeyman's Mercenary Hood",
      "Journeyman's Scholar Cowl",
      "Journeyman's Soldier Helmet",
      "Legendary Adventurer's Hat",
      "Legendary Explorer's Hat",
      "Uncle Frost's Hat",
      "T4",
      "Adept's Assassin Hood",
      "Adept's Cleric Cowl",
      "Adept's Demon Helmet",
      "Adept's Druid Cowl",
      "Adept's Fiend Cowl",
      "Adept's Graveguard Helmet",
      "Adept's Guardian Helmet",
      "Adept's Harvester Cap",
      "Adept's Hellion Hood",
      "Adept's Hunter Hood",
      "Adept's Knight Helmet",
      "Adept's Lumberjack Cap",
      "Adept's Mage Cowl",
      "Adept's Mercenary Hood",
      "Adept's Miner Cap",
      "Adept's Quarrier Cap",
      "Adept's Royal Cowl",
      "Adept's Royal Helmet",
      "Adept's Royal Hood",
      "Adept's Scholar Cowl",
      "Adept's Skinner Cap",
      "Adept's Soldier Helmet",
      "Adept's Stalker Hood"
      # "T5",
      # "Expert's Assassin Hood",
      # "Expert's Cleric Cowl",
      # "Expert's Demon Helmet",
      # "Expert's Druid Cowl",
      # "Expert's Fiend Cowl",
      # "Expert's Graveguard Helmet",
      # "Expert's Guardian Helmet",
      # "Expert's Harvester Cap",
      # "Expert's Hellion Hood",
      # "Expert's Hunter Hood",
      # "Expert's Knight Helmet",
      # "Expert's Lumberjack Cap",
      # "Expert's Mage Cowl",
      # "Expert's Mercenary Hood",
      # "Expert's Miner Cap",
      # "Expert's Quarrier Cap",
      # "Expert's Royal Cowl",
      # "Expert's Royal Helmet",
      # "Expert's Royal Hood",
      # "Expert's Scholar Cowl",
      # "Expert's Skinner Cap",
      # "Expert's Soldier Helmet",
      # "Expert's Stalker Hood",
      # "T6",
      # "Master's Assassin Hood",
      # "Master's Cleric Cowl",
      # "Master's Demon Helmet",
      # "Master's Druid Cowl",
      # "Master's Fiend Cowl",
      # "Master's Graveguard Helmet",
      # "Master's Guardian Helmet",
      # "Master's Harvester Cap",
      # "Master's Hellion Hood",
      # "Master's Hunter Hood",
      # "Master's Knight Helmet",
      # "Master's Lumberjack Cap",
      # "Master's Mage Cowl",
      # "Master's Mercenary Hood",
      # "Master's Miner Cap",
      # "Master's Quarrier Cap",
      # "Master's Royal Cowl",
      # "Master's Royal Helmet",
      # "Master's Royal Hood",
      # "Master's Scholar Cowl",
      # "Master's Skinner Cap",
      # "Master's Soldier Helmet",
      # "Master's Stalker Hood",
      # "T7",
      # "Grandmaster's Assassin Hood",
      # "Grandmaster's Cleric Cowl",
      # "Grandmaster's Demon Helmet",
      # "Grandmaster's Druid Cowl",
      # "Grandmaster's Fiend Cowl",
      # "Grandmaster's Graveguard Helmet",
      # "Grandmaster's Guardian Helmet",
      # "Grandmaster's Harvester Cap",
      # "Grandmaster's Hellion Hood",
      # "Grandmaster's Hunter Hood",
      # "Grandmaster's Knight Helmet",
      # "Grandmaster's Lumberjack Cap",
      # "Grandmaster's Mage Cowl",
      # "Grandmaster's Mercenary Hood",
      # "Grandmaster's Miner Cap",
      # "Grandmaster's Quarrier Cap",
      # "Grandmaster's Royal Cowl",
      # "Grandmaster's Royal Helmet",
      # "Grandmaster's Royal Hood",
      # "Grandmaster's Scholar Cowl",
      # "Grandmaster's Skinner Cap",
      # "Grandmaster's Soldier Helmet",
      # "Grandmaster's Stalker Hood",
      # "T8",
      # "Elder's Assassin Hood",
      # "Elder's Cleric Cowl",
      # "Elder's Demon Helmet",
      # "Elder's Druid Cowl",
      # "Elder's Fiend Cowl",
      # "Elder's Graveguard Helmet",
      # "Elder's Guardian Helmet",
      # "Elder's Harvester Cap",
      # "Elder's Hellion Hood",
      # "Elder's Hunter Hood",
      # "Elder's Knight Helmet",
      # "Elder's Lumberjack Cap",
      # "Elder's Mage Cowl",
      # "Elder's Mercenary Hood",
      # "Elder's Miner Cap",
      # "Elder's Quarrier Cap",
      # "Elder's Royal Cowl",
      # "Elder's Royal Helmet",
      # "Elder's Royal Hood",
      # "Elder's Scholar Cowl",
      # "Elder's Skinner Cap",
      # "Elder's Soldier Helmet",
      # "Elder's Stalker Hood"
    ]
    #
    # @armors = [
    #   "Beginner's Mercenary Jacket",
    #   "T2",
    #   "Novice's Mercenary Jacket",
    #   "Novice's Scholar Robe",
    #   "Novice's Soldier Armor",
    #   "Adventurer's Jacket",
    #   "Explorer's Armor",
    #   "T3",
    #   "Journeyman's Mercenary Jacket",
    #   "Journeyman's Scholar Robe",
    #   "Journeyman's Soldier Armor",
    #   "Legendary Adventurer's Armor",
    #   "Legendary Explorer's Armor",
    #   "T4",
    #   "Adept's Assassin Jacket",
    #   "Adept's Cleric Robe",
    #   "Adept's Demon Armor",
    #   "Adept's Druid Robe",
    #   "Adept's Fiend Robe",
    #   "Adept's Graveguard Armor",
    #   "Adept's Guardian Armor",
    #   "Adept's Harvester Garb",
    #   "Adept's Hellion Jacket",
    #   "Adept's Hunter Jacket",
    #   "Adept's Knight Armor",
    #   "Adept's Lumberjack Garb",
    #   "Adept's Mage Robe",
    #   "Adept's Mercenary Jacket",
    #   "Adept's Miner Garb",
    #   "Adept's Quarrier Garb",
    #   "Adept's Royal Armor",
    #   "Adept's Royal Jacket",
    #   "Adept's Royal Robe",
    #   "Adept's Scholar Robe",
    #   "Adept's Skinner Garb",
    #   "Adept's Soldier Armor",
    #   "Adept's Stalker Jacket",
    #   "T5",
    #   "Expert's Assassin Jacket",
    #   "Expert's Cleric Robe",
    #   "Expert's Demon Armor",
    #   "Expert's Druid Robe",
    #   "Expert's Fiend Robe",
    #   "Expert's Graveguard Armor",
    #   "Expert's Guardian Armor",
    #   "Expert's Harvester Garb",
    #   "Expert's Hellion Jacket",
    #   "Expert's Hunter Jacket",
    #   "Expert's Knight Armor",
    #   "Expert's Lumberjack Garb",
    #   "Expert's Mage Robe",
    #   "Expert's Mercenary Jacket",
    #   "Expert's Miner Garb",
    #   "Expert's Quarrier Garb",
    #   "Expert's Royal Armor",
    #   "Expert's Royal Jacket",
    #   "Expert's Royal Robe",
    #   "Expert's Scholar Robe",
    #   "Expert's Skinner Garb",
    #   "Expert's Soldier Armor",
    #   "Expert's Stalker Jacket",
    #   "T6",
    #   "Master's Assassin Jacket",
    #   "Master's Cleric Robe",
    #   "Master's Demon Armor",
    #   "Master's Druid Robe",
    #   "Master's Fiend Robe",
    #   "Master's Graveguard Armor",
    #   "Master's Guardian Armor",
    #   "Master's Harvester Garb",
    #   "Master's Hellion Jacket",
    #   "Master's Hunter Jacket",
    #   "Master's Knight Armor",
    #   "Master's Lumberjack Garb",
    #   "Master's Mage Robe",
    #   "Master's Mercenary Jacket",
    #   "Master's Miner Garb",
    #   "Master's Quarrier Garb",
    #   "Master's Royal Armor",
    #   "Master's Royal Jacket",
    #   "Master's Royal Robe",
    #   "Master's Scholar Robe",
    #   "Master's Skinner Garb",
    #   "Master's Soldier Armor",
    #   "Master's Stalker Jacket",
    #   "T7",
    #   "Grandmaster's Assassin Jacket",
    #   "Grandmaster's Cleric Robe",
    #   "Grandmaster's Demon Armor",
    #   "Grandmaster's Druid Robe",
    #   "Grandmaster's Fiend Robe",
    #   "Grandmaster's Graveguard Armor",
    #   "Grandmaster's Guardian Armor",
    #   "Grandmaster's Harvester Garb",
    #   "Grandmaster's Hellion Jacket",
    #   "Grandmaster's Hunter Jacket",
    #   "Grandmaster's Knight Armor",
    #   "Grandmaster's Lumberjack Garb",
    #   "Grandmaster's Mage Robe",
    #   "Grandmaster's Mercenary Jacket",
    #   "Grandmaster's Miner Garb",
    #   "Grandmaster's Quarrier Garb",
    #   "Grandmaster's Royal Armor",
    #   "Grandmaster's Royal Jacket",
    #   "Grandmaster's Royal Robe",
    #   "Grandmaster's Scholar Robe",
    #   "Grandmaster's Skinner Garb",
    #   "Grandmaster's Soldier Armor",
    #   "Grandmaster's Stalker Jacket",
    #   "T8",
    #   "Elder's Assassin Jacket",
    #   "Elder's Cleric Robe",
    #   "Elder's Demon Armor",
    #   "Elder's Druid Robe",
    #   "Elder's Fiend Robe",
    #   "Elder's Graveguard Armor",
    #   "Elder's Guardian Armor",
    #   "Elder's Harvester Garb",
    #   "Elder's Hellion Jacket",
    #   "Elder's Hunter Jacket",
    #   "Elder's Knight Armor",
    #   "Elder's Lumberjack Garb",
    #   "Elder's Mage Robe",
    #   "Elder's Mercenary Jacket",
    #   "Elder's Miner Garb",
    #   "Elder's Quarrier Garb",
    #   "Elder's Royal Armor",
    #   "Elder's Royal Jacket",
    #   "Elder's Royal Robe",
    #   "Elder's Scholar Robe",
    #   "Elder's Skinner Garb",
    #   "Elder's Soldier Armor",
    #   "Elder's Stalker Jacket"
    # ]
    #
    # @shoes = [
    #   "Beginner's Mercenary Shoes",
    #   "T2"
    #   "Novice's Mercenary Shoes",
    #   "Novice's Scholar Sandals",
    #   "Novice's Soldier Boots",
    #   "Adventurer's Shoes",
    #   "Explorer's Boots",
    #   "T3",
    #   "Journeyman's Mercenary Shoes",
    #   "Journeyman's Scholar Sandals",
    #   "Journeyman's Soldier Boots",
    #   "Legendary Adventurer's Boots",
    #   "Legendary Explorer's Boots",
    #   "T4",
    #   "Adept's Assassin Shoes",
    #   "Adept's Cleric Sandals",
    #   "Adept's Demon Boots",
    #   "Adept's Druid Sandals",
    #   "Adept's Fiend Sandals",
    #   "Adept's Graveguard Boots",
    #   "Adept's Guardian Boots",
    #   "Adept's Harvester Workboots",
    #   "Adept's Hellion Shoes",
    #   "Adept's Hunter Shoes",
    #   "Adept's Knight Boots",
    #   "Adept's Lumberjack Workboots",
    #   "Adept's Mage Sandals",
    #   "Adept's Mercenary Shoes",
    #   "Adept's Miner Workboots",
    #   "Adept's Quarrier Workboots",
    #   "Adept's Royal Boots",
    #   "Adept's Royal Sandals",
    #   "Adept's Royal Shoes",
    #   "Adept's Scholar Sandals",
    #   "Adept's Skinner Workboots",
    #   "Adept's Soldier Boots",
    #   "Adept's Stalker Shoes",
    #   "T5",
    #   "Expert's Assassin Shoes",
    #   "Expert's Cleric Sandals",
    #   "Expert's Demon Boots",
    #   "Expert's Druid Sandals",
    #   "Expert's Fiend Sandals",
    #   "Expert's Graveguard Boots",
    #   "Expert's Guardian Boots",
    #   "Expert's Harvester Workboots",
    #   "Expert's Hellion Shoes",
    #   "Expert's Hunter Shoes",
    #   "Expert's Knight Boots",
    #   "Expert's Lumberjack Workboots",
    #   "Expert's Mage Sandals",
    #   "Expert's Mercenary Shoes",
    #   "Expert's Miner Workboots",
    #   "Expert's Quarrier Workboots",
    #   "Expert's Royal Boots",
    #   "Expert's Royal Sandals",
    #   "Expert's Royal Shoes",
    #   "Expert's Scholar Sandals",
    #   "Expert's Skinner Workboots",
    #   "Expert's Soldier Boots",
    #   "Expert's Stalker Shoes",
    #   "T6",
    #   "Master's Assassin Shoes",
    #   "Master's Cleric Sandals",
    #   "Master's Demon Boots",
    #   "Master's Druid Sandals",
    #   "Master's Fiend Sandals",
    #   "Master's Graveguard Boots",
    #   "Master's Guardian Boots",
    #   "Master's Harvester Workboots",
    #   "Master's Hellion Shoes",
    #   "Master's Hunter Shoes",
    #   "Master's Knight Boots",
    #   "Master's Lumberjack Workboots",
    #   "Master's Mage Sandals",
    #   "Master's Mercenary Shoes",
    #   "Master's Miner Workboots",
    #   "Master's Quarrier Workboots",
    #   "Master's Royal Boots",
    #   "Master's Royal Sandals",
    #   "Master's Royal Shoes",
    #   "Master's Scholar Sandals",
    #   "Master's Skinner Workboots",
    #   "Master's Soldier Boots",
    #   "Master's Stalker Shoes",
    #   "T7",
    #   "Grandmaster's Assassin Shoes",
    #   "Grandmaster's Cleric Sandals",
    #   "Grandmaster's Demon Boots",
    #   "Grandmaster's Druid Sandals",
    #   "Grandmaster's Fiend Sandals",
    #   "Grandmaster's Graveguard Boots",
    #   "Grandmaster's Guardian Boots",
    #   "Grandmaster's Harvester Workboots",
    #   "Grandmaster's Hellion Shoes",
    #   "Grandmaster's Hunter Shoes",
    #   "Grandmaster's Knight Boots",
    #   "Grandmaster's Lumberjack Workboots",
    #   "Grandmaster's Mage Sandals",
    #   "Grandmaster's Mercenary Shoes",
    #   "Grandmaster's Miner Workboots",
    #   "Grandmaster's Quarrier Workboots",
    #   "Grandmaster's Royal Boots",
    #   "Grandmaster's Royal Sandals",
    #   "Grandmaster's Royal Shoes",
    #   "Grandmaster's Scholar Sandals",
    #   "Grandmaster's Skinner Workboots",
    #   "Grandmaster's Soldier Boots",
    #   "Grandmaster's Stalker Shoes",
    #   "T8",
    #   "Elder's Assassin Shoes",
    #   "Elder's Cleric Sandals",
    #   "Elder's Demon Boots",
    #   "Elder's Druid Sandals",
    #   "Elder's Fiend Sandals",
    #   "Elder's Graveguard Boots",
    #   "Elder's Guardian Boots",
    #   "Elder's Harvester Workboots",
    #   "Elder's Hellion Shoes",
    #   "Elder's Hunter Shoes",
    #   "Elder's Knight Boots",
    #   "Elder's Lumberjack Workboots",
    #   "Elder's Mage Sandals",
    #   "Elder's Mercenary Shoes",
    #   "Elder's Miner Workboots",
    #   "Elder's Quarrier Workboots",
    #   "Elder's Royal Boots",
    #   "Elder's Royal Sandals",
    #   "Elder's Royal Shoes",
    #   "Elder's Scholar Sandals",
    #   "Elder's Skinner Workboots",
    #   "Elder's Soldier Boots",
    #   "Elder's Stalker Shoes"
    # ]
  end
end
